spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 2028264570
  #文件上传的配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.study.demo.mybatis.entity


#阿里云oss
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tMLebW35sdP9fWqyEH3
    accessKeySecret: gkTouhQ6VqfrmoetuVh21Pp1JgJi5D
    bucketName: web-study-sxbm
#server:
#  port: 8080

#spring事务管理
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug